# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Fabricio Arend Torres
title: Machine Learning - PhD Student
email: fabricio.arendtorres@gmail.com
website: https://fabricioarendtorres.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  FabricioArendTorres
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: fabricio-arend-torres
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/fabricio.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Fabricio, a Computer Scientist working in the area of Machine Learning, Data Science & Statistics.
  I'm currently a PhD Student at the University of Basel, where I'm researching ways to model different kinds of ornithological data.
  The applications range from modeling migration events based on radar data to estimating species distribution models of birds based on citizen-science observations.
  
  On the methodological side my interest lie in Gaussian Processes, Density Estimation (including deep generative models and generative flows), and Implicit Representation Networks.
  Within the University I'm further involved in mentoring Bachelor's and Master's theses and assist in the 'Scientific Computing' lecture held at our department. 
  Finally, I regularly review papers for some of the major ML Conferences (NeurIPS, ICML, ICLR).

  In more practical terms I have worked quite a bit with the most common Machine Learning and Data Science frameworks, notable mentions being Tensorflow, Pytorch and libraries for scalable Gaussian Process (GPflow, GPytorch).
  Aside from that, I'm comfortable with the general scientific stack of libraries within python (numpy, scipy, pandas, scikit-learn, matplotlib).
  As the work within my projects includes extensive preprocessing and exploratory analysis, I have some experience working with spatiotemporal geo-data and the data formats common within that area.
  While there is a wide range of frameworks and languages I haven't worked with, I always enjoy delving into new technologies and frameworks.

  A more complete list of programming languages, frameworks and tools I've worked with is listed below.
  The level of familiarity is indicated with stars, ranging from basic concepts (*) to extensive experience (***).
  - Programming languages: <mark>Python</mark> (***), <mark>R</mark> (*), <mark>Javascript</mark> (*)
  - Deep / Machine Learning: <mark>Tensorflow</mark>1 (*) & 2 (**).  <mark>Pytorch</mark> (**), <mark>scikit-learn</mark>
  - Gaussian Processes: <mark>GPflow</mark>(***), <mark>GPytorch</mark>(*)
  - Exploratory Data Analysis & Preprocessing: <mark>Python Scientific Stack</mark> (**)
  - Data Extraction: <mark>pandas</mark>(***), <mark>SQL</mark>(**), <mark>Google Earth Engine</mark>(*)
  - Workflow: <mark>conda/virtenv/pip</mark>(**), <mark>git</mark>(**), <mark>linux</mark>(**), <mark>SLURM</mark>(*)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Estimating relative abundance of nocturnal migrant species
        #link: github.com/TODO
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          todo
        description: | # this will include new lines to allow paragraphs
          todo

      - layout: top-middle
        title: Scalable Gaussian Processes for spatio-temporal interpolation of migration events 
        #link: github.com/TODO
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          todo
        description: | # this will include new lines to allow paragraphs
          todo

      - layout: top-middle
        title: Simulating Stochastic Paths for estimating path-level uncertainty 
        #link: github.com/TODO
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          todo
        description: | # this will include new lines to allow paragraphs
          todo

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Basel
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: PhD Student
        caption: 2019 - Present
        description: | # this will include new lines to allow paragraphs
            Publications:
            Keller, Sebastian Mathias, Maxim Samarin, Fabricio Arend Torres, Mario Wieser, and Volker Roth. 
            "Learning extremal representations with deep archetypal analysis." International Journal of Computer Vision 129, no. 4 (2021): 805-820.

            Sebastian M. Keller*, Fabricio Arend Torres*, Maxim Samarin, Mario Wieser and Volker Roth.
            Exploring Data Through Archetypal Representatives, NeurIPS Learning Meaningful Representations of Life Workshop 2019, Canada. (*equal contribution)

    content:
      - layout: left
        title: University of Basel
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Student Assistant for Biomedical Data Analysis
        caption: Nov 2016 - Dec 2017
        description: | # this will include new lines to allow paragraph
          Assistance in a research project for analysing Next Generation Sequencing Data in context of modeling HIV treatment outcomes.
          Here I gathered first practical experiences with processing large scale data, aligning genome sequencing data, and general feature engineering.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Basel
        caption: 2016 - 2018
        sub_title: MSc Computer Science with focus on 'Machine Intelligence'
        description: | # this will include new lines to allow paragraphs
          In context of my master's thesis 'Sampling and Annealing for Dependency Subnetwork Estimation' I implemented and extended a model for estimating sparse dependency networks between variables.
          The model was applied to HIV data for detecting possible connections between resistance-relevant mutations and treatment outcome.

          This project allowed me to get some insight into more classical Bayesian models as well as MCMC sampling schemes.

      - layout: left
        title: University of Basel
        caption: 2012 - 2016
        sub_title: BSc Computer Science
        quote: >
          todo
        description: | # this will include new lines to allow paragraphs
          todo

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      todo

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
